# Change these first
owner: Kail0 # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: GACR
    url: https://gacr.cz/
  - name: Mail
    url: https://pigeon.gacr.cz/owa/
  - name: Helpdesk GACR
    url: https://info.gacr.cz
  - name: Kailo
    url: https://kailo.io
  - name: Kailo | Speedtest
    url: https://speedtest.kailo.io
  - name: GRIS
    url: https://gris.cz/

  # - name: Hacker News
  #   url: https://news.ycombinator.com
  # - name: Broken Site
  #   url: https://thissitedoesnotexist.com
  # - name: Secret Site
  #   url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.gacr.cz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://gacr.cz/wp-content/uploads/2019/10/gacr_logo_cs.svg
  name: Kailo monitor
  introTitle: "**Lorem** ipsium."
  introMessage: Lorem
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Time is but a relative concept

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
